version: '3'
services:
  webpack:
    build: .
    command: npm run webpack:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  patternlab:
    build: .
    command: npm run pl:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules