version: '3'
services:
  webpack:
    build: .
    command: webpack:dev
    volumes:
      - .:/usr/local/patternlab/
      - /usr/local/patternlab/node_modules/
  patternlab:
    build: .
    command: pl:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/local/patternlab/
      - /usr/local/patternlab/node_modules/